import localFont from 'next/font/local';
import './globals.css';
import Navbar from '@/components/Shared/Navbar';
import Footer from '@/components/Shared/Footer';
import ActiveProvider from '@/contexts/ActiveProvider';
import ThemeProvider from '@/contexts/ThemeProvider';
import TanStackQueryProvider from '@/contexts/TanStackQueryProvider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Developer Saif',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      suppressHydrationWarning
      className="overflow-y-scroll scroll-smooth scrollbar-thin scrollbar-track-blue-200 scrollbar-thumb-[#0082C4]"
    >
      <head>
        <link rel="shortcut icon" href="logo.png" type="image/x-icon" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-base-100 antialiased dark:bg-background`}
      >
        <ThemeProvider>
          <TanStackQueryProvider>
            <ActiveProvider>
              <Navbar />
              {children}
              <Footer />
            </ActiveProvider>
          </TanStackQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
