import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar";
import Footer from "@/components/Shared/Footer";
import ActiveProvider from "@/contexts/ActiveProvider";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Developer Saif",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" data-theme="light">
      <head>
        <link rel="shortcut icon" href="logo.png" type="image/x-icon" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  dark:bg-background bg-base-100`}
      >
        <ActiveProvider>
          <Navbar />
          {children}
          <Footer />
        </ActiveProvider>
      </body>
    </html>
  );
}
